### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by vr8hub** [pbryan/jean-jacques-rousseau_the-social-contract_g-d-h-cole#1]
- [x] Typogrify makes changes that should be accepted.
- [ ] The commit from running semanticate is missing. It appears that ff9de4a "Add Semantics" includes it, but it also includes manual semantic changes, as well as removing italics from "i.e." (and maybe other changes; it's hard to tell.) Those should be (at least) three different commits. Since the majority (I think) of the work was done in semanticate, doing a rebase to split them should be fairly easy; if you haven't done a rebase before, just reply here and I'll give you some instructions.
- [ ] It would appear that almost none of the emphasized words are actual emphasis. In most of the cases I looked at, it's instances of him introducing a word (e.g. "The words _slave_ and _right_ contradict each other…"); this is covered by [SEMoS 8.2.10.1](https://standardebooks.org/manual/1.8.0/single-page#8.2.10.1). (This is quite common in 18th century works; I had a tone of this in Gibbon as well.) In other cases, they are either books (e.g. "… which the _Social Contract_ provides …,") and should be italics and tagged, or non-English words/phrases that should be italics and tagged, or in M-W (e.g. en masse) and therefore should not have italics at all. You will need to make a pass through and look at all of the `<em>` tags and correct the ones that need it, which might be most of them, based on the sample I looked at. (This also means f16c25d was an incorrect reversion; the original change was correct.)
- [ ] There are also italics that should be removed, e.g. de jure, de facto, etc.; see [SEMoS 8.2.9.4](https://standardebooks.org/manual/1.8.0/single-page#8.2.9.4).
- [ ] Re the language code of "vec" in the endnotes, I don't see that on the [ISO list](https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes), and, beyond that, that would appear to be a title, and we don't tag proper names (https://standardebooks.org/manual/1.8.0/single-page#8.2.9.2).
- [ ] Commit 5fc8517 is removing ligatures (still editorial), not modernizing spelling; the message should be updated accordingly. (This is also a rebase, albeit a very easy one; see above.)
- [ ] Commit 16eaa21d "Cleanup punctuation" sounds like it's changing the punctuation, which would either be editorial or transcription corrections. What it's actually doing is moving punctuation outside of italic tags, so let's say that in the commit message. (Having looked further, you used "Cleanup punctuation in italics" in a later commit, which would be fine here as well.)
- [ ] The commit message in ec0fe912 is the one we specify to use when running the british2american conversion. This book wasn't using British quotation (it used double quotes throughout), it just had a couple of isolated quotes that were the wrong ones (which is quite common in PD works). The message should just reflect correcting a couple of quotes.
- [ ] Commit b24841f: we do not correct "none the less," "worth while," or "in so far": those are all over the corpus. They will need to be reverted. (And what's left, I believe, is again just a ligature correction, not a modernize spelling.)
- [ ] In add9cd6, I don't believe the two Latin quotes in the endnotes (note-29 and -42) need quotation marks, since no one is saying them. At least I know we have plenty of those types of quotes in the corpus, without the marks.
- [ ] Roman numerals should be uppercase, [SEMoS 8.8.5.1](https://standardebooks.org/manual/1.8.0/single-page#8.8.5.1).
- [ ] I happened to see an instance of "repayed"; that should be modernized (editorial) to "repaid."

**Comment by pbryan** [comment]
> Re the language code of "vec" in the endnotes, I don't see that on the [ISO list](https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes), and, beyond that, that would appear to be a title, and we don't tag proper names (https://standardebooks.org/manual/1.8.0/single-page#8.2.9.2).

I've de-italicized (and untagged) the proper name. The other is a publication though, which I believe is a Venetian title. According to the [Wikipedia article](https://en.wikipedia.org/wiki/Venetian_language) on the Venetian language, the ISO 639-2 code is `vec`. This code seems most likely to have been included in [ISO 639:2023](https://www.iso.org/standard/74575.html), in which [codes for ancient languages](https://blog.ansi.org/iso-639-codes-for-ancient-languages/) were added. [Additional support for this here](https://iso639-3.sil.org/code/vec), though not authoritative. If further proof is required, I'll try to lay hands on the actual ISO standard.

**Comment by vr8hub** [comment]
It is not 639-2 but 639-3 (according to the article), which is why I didn't find it. According to [this](https://cardinals.fiu.edu/bios1622.htm), it was written in Italian.
>The source adds that the matter is regarded as problématique and that the hatred the future cardinal had for Venice made him write in Italian a traité in which he examined the liberty of that republic. At least, the most common opinion attributed the work to him. It is entitled Squittinio della liberta Veneta.

**Comment by pbryan** [comment]
> The source adds that the matter is regarded as problématique and that the hatred the future cardinal had for Venice made him write in Italian a traité in which he examined the liberty of that republic. At least, the most common opinion attributed the work to him. It is entitled Squittinio della liberta Veneta.

The title itself doesn't seem to translate well from Italian. I'll dig into this a bit more.

**Comment by pbryan** [comment]
I am *definitely* not fluent in Italian (or ancient Venetian). The word that hung me up was “Squitinio.” Based on scouring the Interwebs and consulting LLMs, it seems likely to me that the text contains archaic Italian, with possible Venetian influences. I'm interested in anything you uncover.

**Comment by pbryan** [comment]
> In other cases, they are either books (e.g. "… which the Social Contract provides …,")

This is an isolated case where it appears to me that the author's intent is to call out the concept of the *Social Contract*, not to refer to his own work by name. This is the only instance where an italicized *Social Contract* is not semantically marked-up as a publication; all other instances are the Cole referring to Rousseau's work by name.

**Comment by pbryan** [comment]
I've completed the tasks listed above.

**Comment by pbryan** [comment]
OK, I think I need a bit of guidance on the principles behind this. If these were italic in the original text and were not intended as emphasis, what were they?

**Comment by vr8hub** [comment]
Which ones are you referring to?
For the first three, we've already seen multiple instances of things that were italicized originally that shouldn't be by SE's style guide. I would say these fall into the same area.
For Institutes, it should be italicized, but it's definitely not emphasis, it's a book, and should be tagged as such, [SEMoS 8.2.11.2](https://standardebooks.org/manual/1.8.0/single-page#8.2.11.2).
For the last, they're no different than en masse, etc.; they're words/phrases that were originally loanwords from another language, that are considered "English" today (by virtue of being in M-W), and therefore are not italicized per SE's style guide. While that's occasionally hard to tell, it's usually not, because in context the emphasis doesn't really make sense. In this case, every occurrence of maxima/um is italicized, and emphasis isn't needed in any of them, and it's far enough back (mid-eighteenth century) that maxima/um would still have been considered non-English.
This is, of course, an inexact science, which is why I checked with Alex before we started. I *thought* that 8.2.10.1 applied, but I wanted to make sure before you made a bunch of changes.

**Comment by pbryan** [comment]
OK, thanks. Alright, I've removed emphasis on the noted English words and phrases. I now have publication semantic on Calvin's *Institute*.

**Comment by vr8hub** [comment]
Awesome. By "… these fall into the same area," I meant they should be quoted, as with the other terms that were changed. With those three changes, I believe this is ready for Alex.

**Comment by pbryan** [comment]
I've rebased the last commit and added the de-emphasis and quotation of unfinished works to its own commit.
